// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSjVmt_Vvbddl7L8rUCgW26-TFb-v_R88',
    appId: '1:937155925778:web:7699eae45c7deb060005cb',
    messagingSenderId: '937155925778',
    projectId: 'smart-event-platform-2e99f',
    authDomain: 'smart-event-platform-2e99f.firebaseapp.com',
    storageBucket: 'smart-event-platform-2e99f.firebasestorage.app',
    measurementId: 'G-1XL4ZYXYJG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6pkz02MrzO6odgskDcF1uGYswtplJO40',
    appId: '1:937155925778:android:ded03c78b9ca31160005cb',
    messagingSenderId: '937155925778',
    projectId: 'smart-event-platform-2e99f',
    storageBucket: 'smart-event-platform-2e99f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOAFp03mC3xSirgNhlL_wEKeiR0Zqhcvg',
    appId: '1:937155925778:ios:fa477e3859b008340005cb',
    messagingSenderId: '937155925778',
    projectId: 'smart-event-platform-2e99f',
    storageBucket: 'smart-event-platform-2e99f.firebasestorage.app',
    iosBundleId: 'com.example.smartEventPlatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOAFp03mC3xSirgNhlL_wEKeiR0Zqhcvg',
    appId: '1:937155925778:ios:fa477e3859b008340005cb',
    messagingSenderId: '937155925778',
    projectId: 'smart-event-platform-2e99f',
    storageBucket: 'smart-event-platform-2e99f.firebasestorage.app',
    iosBundleId: 'com.example.smartEventPlatform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSjVmt_Vvbddl7L8rUCgW26-TFb-v_R88',
    appId: '1:937155925778:web:c53136fe245fcb170005cb',
    messagingSenderId: '937155925778',
    projectId: 'smart-event-platform-2e99f',
    authDomain: 'smart-event-platform-2e99f.firebaseapp.com',
    storageBucket: 'smart-event-platform-2e99f.firebasestorage.app',
    measurementId: 'G-49NKTZKJE1',
  );
}
